### PR TITLE
Removed MongoSkin

### PR DESCRIPTION
**Pull request by NicerHugs**
rather than try to keep mongoskin, which hasn't been updated since mongo had new release, just removed it and added back the same functionality without it.

### CODE REVIEW

**Comment by kjschulz** [comment]
Just started playing around with this app.  Does this PR allow you to make PUT and DELETE requests once deployed to heroku?  I'm currently only able to POST and GET.

**Comment by NicerHugs** [comment]
Yes, PR should fix this problem.

**Comment by kjschulz** [comment]
Excellent, thanks!

**Comment by kjschulz** [comment]
:+1:

**Comment by mason-stewart** [comment]
@NicerHugs wowzer thanks for hacking on poor old tiny server. At this point I assume TIY staff know what they're doing when submitting PRs, so I'm happy to merge this! I'll also add you as a collab. Enjoy!

+1

**Comment by kjschulz** [comment]
Thanks for merging @masondesu!.  @NicerHugs, I just merged in the latest code changes into my heroku clone and deployed and am still unable to PUT or DELETE...I get `Internal Server Error`.  I can still GET and POST.  Just FYI.

**Comment by NicerHugs** [comment]
@kjschulz Sorry to hear you're still getting errors. I have two instances of the app running on my heroku acct - one deployed from my fork, and one from @masondesu's post merge, and both versions are successfully allowing PUT and DELETE requests. FWIW, PUT and DELETE are only supported for individual documents, not collections. The endpoint is `/collections/:collectionName/:_id` Hope that helps.

**Comment by kjschulz** [comment]
Thanks @NicerHugs, I haven't had much time to look into it lately but in further investigation this morning, it looks like the issue was that I was assigning my own `_id` value and it will `POST` fine that way.  However, it seems that you are not able to make `DELETE` or `PUT` operations that way.  If I just let Mongo generate the `_id` for me, I get the full REST functionality. 

So TLDR is if we need to assign an ID attribute generated by the app consuming the API and not Mongo, we should use another param for this and still allow Mongo to generate the `_id`...then simply query/filter by the custom ID attribute to get the `_id` to perform operations on.

**Comment by mason-stewart** [comment]
@kjschulz fwiw, the convention is _not_ to assign or generate the ID client-side. Not to say that you couldn't do it that way; I've just never worked on an app where the front end was responsible for generating IDs. Letting the API or backend generate those avoids collisions with two or more clients generating the same ID. This is typical with all of the RESTful APIs I've worked with. While tiny-server is by no means strictly RESTful, it does follow this convention at least.

**Comment by kjschulz** [comment]
@masondesu I totally agree and I should not have taken that approach when testing this library.  It's a strange use case in this instance.  It's a mobile app that utilizes a locally stored collection (sqlite) whereby I needed to be able to pass the id generated locally when and only when it's safe to persist to a trusted network spread over long periods of time.  Since I'm was only using this library as an API quick mock tool the issue could have been easily avoided by just passing that locally generated Id as another param...which I've done and now it works well.  Ultimately, as you mentioned, that's the right way to proceed and certainly the way it would need to work in production anyway.  I just didn't think of that when throwing everything together the first time.  Thanks again for the feedback!  Great tool :+1:

**Pull request merged**
